name: canon-env
channels:
  - defaults
  - pytorch
dependencies:
  - blas=1.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpuonly=2.0
  - expat=2.7.3
  - filelock=3.20.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=73.1
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.50
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - nodejs=24.10.0
  - openjpeg=2.5.2
  - openssl=3.0.18
  - pillow=11.1.0
  - pip=25.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==3.7.1
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - easyocr==1.7.2
      - exceptiongroup==1.3.1
      - fastapi==0.104.1
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - httptools==0.7.1
      - imageio==2.37.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - matplotlib==3.10.7
      - ninja==1.13.0
      - numpy==1.24.3
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.0.3
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - psutil==7.1.3
      - pyclipper==1.4.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.27.0
      - sympy==1.13.1
      - tifffile==2025.5.10
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.228
      - ultralytics-thop==2.0.18
      - uvicorn==0.24.0
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: C:\Users\user\miniconda3\envs\canon-env
